### ISSUE TITLE
Refactor DataFlowAbstraction so that it has only two fields: statement and variable

### ISSUE THREAD

**Issue by pauloborba** [spgroup/conflict-static-analysis#21]
private Local local;
     private JInstanceFieldRef localInstanceField;		     private JInstanceFieldRef localInstanceField;
     private JArrayRef localJArrayRef;
     private StaticFieldRef localStaticFieldRef;

**Comment by barbosamaatheus** [comment]
Currently at #31 I add the attributes:

```
private Statement stmt;
private Value value;
```

However, an effort is needed to refactor the other analyzes that still use the other fields. In a quick analysis, I believe only intra OA analysis that uses these fields.
