### ISSUE TITLE
Refactor overriding assignment abstraction so that we have two lists

### ISSUE THREAD

**Issue by pauloborba** [spgroup/conflict-static-analysis#22]

**Comment by pauloborba** [comment]
refactor OverridingAssignmentFieldsRefAnalysis.java

**Comment by barbosamaatheus** [comment]
the interprocedural analysis in #31 will already have two lists... This issue will remain open for refactoring of the intraprocedural analysis in the future.

**Comment by pauloborba** [comment]
@barbosamaatheus better to close this one and open a refactoring issue.
