### ISSUE TITLE
Integrate different overriding assignment implementations for performance and experiment reasons

### ISSUE THREAD

**Issue by pauloborba** [spgroup/conflict-static-analysis#23]

**Comment by pauloborba** [comment]
refactor OverridingAssignmentFieldsRefAnalysis.java

**Comment by barbosamaatheus** [comment]
@pauloborba do you have a better description for this issue? Is it just a matter of adding an interprocedural analysis, for example?

**Comment by pauloborba** [comment]
> @pauloborba do you have a better description for this issue? Is it just a matter of adding an interprocedural analysis, for example?

that's it @barbosamaatheus !

**Comment by barbosamaatheus** [comment]
> > @pauloborba , você tem uma descrição melhor para esse problema? É só adicionar uma análise interprocedural, por exemplo?
> 
> é isso @barbosamaatheus !

@pauloborba In this case, I already have an issue for that. I think we can close this one.
See #31
