### ISSUE TITLE
Soot Setup for Source Sink Confluence Analysis

### ISSUE THREAD

**Issue by LSinzker** [spgroup/conflict-static-analysis#3]
With the current setup Soot optimizes the code before running the analysis, this way it ends up erasing variable references that have a constant attributed to them, preventing conflict detection by the analyzer if such attribution happens to be a line of interest, such as a Source or Sink (or left, right).
A case such as this:

public void foo(){
    int x = 1;
    int y = 2;

    x = 10;     //left

    y++;         //right

    System.out.println(x+y);
}

Should yield a conflict, however, it doesn't.

**Comment by pauloborba** [comment]
OK, good to know @LSinzker. As an example/test-case, it would be better to insert a separator (line) between //left and //right because without such separator we would have a merge conflict, so this case would not even reach our soot tool.

**Comment by LSinzker** [comment]
Thanks! Fixed.
