### ISSUE TITLE
Confluent Tainted Analysis

### ISSUE THREAD

**Issue by rbonifacio** [spgroup/conflict-static-analysis#5]
This feature is a new variant we should add to our set of analysis algorithms. It builds upon the following features:

- intraprocedural
- transitive definitions (tainted analysis)
- confluence (like our current source-sink confluent algorithm)

**Comment by rbonifacio** [comment]
Hi @LSinzker , could you please work on this issue? Let me know if you need any help.

**Comment by LSinzker** [comment]
Sure!
